### ISSUE TITLE
Gestion de l'inventaire avec des CrafItem

### ISSUE THREAD

**Issue by Isammoc** [algorys/agshmne#22]
Les CraftItems ont une `quality` si j'ai bien compris. Qui sert à savoir si la qualité de l'objet qui va être créée sera aussi bonne que ses composants...

Malheureusement, les `CrafItem`s sont stackable. Du coup, on n'aura qu'un seul objet `CrafItem` par class avec la qualité du premier dans la pile...

Comment gérer la situation d'avoir un bout de bois de mauvaise qualité et un bout de bois de qualité moyenne ?

**Comment by algorys** [comment]
Je suis justement en train de revoir ça, la qualité va disparaitre au profit du type de materiaux

**Comment by algorys** [comment]
N'est plus d'actualités car refonte de la gestion d'inventaire 9d37f9a
