### ISSUE TITLE
Abandonned?

### ISSUE THREAD

**Issue by Isammoc** [algorys/agshmne#89]
Is this project still active?

**Comment by algorys** [comment]
For the moment no ... lack of time and on quite a lot of other projects at the moment. 

Maybe one day...

**Comment by Isammoc** [comment]
Perhaps a badge as this one:

[![Project Status: Suspended – Initial development has started, but there has not yet been a stable, usable release; work has been stopped for the time being but the author(s) intend on resuming work.](http://www.repostatus.org/badges/latest/suspended.svg)](http://www.repostatus.org/#suspended)

```
[![Project Status: Suspended – Initial development has started, but there has not yet been a stable, usable release; work has been stopped for the time being but the author(s) intend on resuming work.](http://www.repostatus.org/badges/latest/suspended.svg)](http://www.repostatus.org/#suspended)

```

Reference: http://www.repostatus.org/

**Comment by algorys** [comment]
Thanks for the tip.

Done.
